// Error codes
#define LOGGER_HUFFMAN_OK  						0
#define	ERR_LIST_COUNT							9
#define ERR_LOGGER_PASSPORT_SEGMENTATION_FAULT	-710
#define ERR_LOGGER_PASSPORT_ABRT           		-711
#define ERR_LOGGER_PASSPORT_COMMAND_LINE   		-712
#define ERR_LOGGER_PASSPORT_COMMAND_LINE_HELP	-713
#define ERR_LOGGER_PASSPORT_INSUFFICIENT_MEMORY	-714
#define ERR_LOGGER_PASSPORT_INSUFFICIENT_PARAMS	-715
#define ERR_LOGGER_PASSPORT_PARAM_INVALID		-716
#define ERR_LOGGER_PASSPORT_NO_DATA      		-717
#define ERR_LOGGER_PASSPORT_INVALID_FORMAT		-718

#define ERR_MESSAGE								"Error "
#define ERR_DEBUG								"Info "
#define ERR_WARNING								"Warning "
#define ERR_UNKNOWN_ERROR_CODE					"Unknown error code "
